{
 "title": "Asp net core - Services",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(http_requests_received_total, app)"
    }
   },
   {
    "name": "pods",
    "label": "pods",
    "query": {
     "query": "label_values(http_requests_received_total{app =~ \"$app\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "controllers",
    "label": "controllers",
    "query": {
     "query": "label_values(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name=~ \"$pods\"}, controller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "graph",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller = \"\"}[1m]))",
     "legendFormat": "(None)"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller = \"\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[1m])) by (controller)",
     "legendFormat": "{{kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{ app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\" }[1m])) by (controller)",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{ app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller = \"\" }[1m])) by (controller)"
    }
   ]
  },
  {
   "title": "Request duration (controller-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Healthchecks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status {app=~\"$app\", kubernetes_pod_name=~\"$pods\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container_name=~\"$app\", pod=~\"$pods\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_in_progress{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}",
     "legendFormat": "{{kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}",
     "legendFormat": "{{kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"} /1024/1024",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name!=\"\", container=~\"$app\", pod=~\"$pods\"}) by (pod_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{ app=~\"$app\", kubernetes_pod_name=~\"$pods\"} /1024/1024",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name }}-Generation-{{generation}}"
    }
   ]
  }
 ]
}